export const mbtiArray = [
  {
    type: "intj",
    msg: 1,
    people: 1,
    color: "#C3C3C3",
    realTime: "off",
  },
  {
    type: "intp",
    msg: 2,
    people: 1,
    color: "#55545A",
    realTime: "off",
  },
  {
    type: "entj",
    msg: 3,
    people: 1,
    color: "#37373F",
    realTime: "off",
  },
  {
    type: "entp",
    msg: 0,
    people: 1,
    color: "#B62135",
    realTime: "off",
  },
  {
    type: "infj",
    msg: 0,
    people: 1,
    color: "#64AECB",
    realTime: "off",
  },
  {
    type: "infp",
    msg: 0,
    people: 1,
    color: "#66C8BB",
    realTime: "off",
  },
  {
    type: "enfj",
    msg: 0,
    people: 1,
    color: "#13A5B4",
    realTime: "off",
  },
  {
    type: "enfp",
    msg: 0,
    people: 1,
    color: "#13A5B4",
    realTime: "off",
  },
  {
    type: "istj",
    msg: 0,
    people: 1,
    color: "#55545A",
    realTime: "off",
  },
  {
    type: "isfj",
    msg: 0,
    people: 1,
    color: "#F4BF59",
    realTime: "off",
  },
  {
    type: "esfj",
    msg: 0,
    people: 1,
    color: "#DA5A8B",
    realTime: "off",
  },
  {
    type: "estj",
    msg: 0,
    people: 1,
    color: "#5CA286",
    realTime: "off",
  },
  {
    type: "istp",
    msg: 0,
    people: 1,
    color: "#363E62",
    realTime: "off",
  },
  {
    type: "isfp",
    msg: 0,
    people: 1,
    color: "#66C8BB",
    realTime: "off",
  },
  {
    type: "estp",
    msg: 0,
    people: 1,
    color: "#C92F37",
    realTime: "off",
  },
  {
    type: "esfp",
    msg: 0,
    people: 1,
    color: "#F5C012",
    realTime: "off",
  },
];

export const mbtiColorArray = {
  intj: "C3C3C3",
  intp: "91ADB9",
  entj: "37373F",
  entp: "B62135",
  infj: "64AECB",
  infp: "66C8BB",
  enfj: "13A5B4",
  enfp: "13A5B4",
  istj: "55545A",
  isfj: "F4BF59",
  esfj: "DA5A8B",
  estj: "5CA286",
  istp: "363E62",
  isfp: "66C8BB",
  estp: "C92F37",
  esfp: "F5C012",
};

export const mbtiPronArray = {
  intj: "인티제",
  intp: "인팁",
  entj: "엔티제",
  entp: "엔팁",
  infj: "인프제",
  infp: "인프피",
  enfj: "엔프제",
  enfp: "엔프피",
  istj: "잇티제",
  isfj: "잇프제",
  esfj: "엣프제",
  estj: "엣티제",
  istp: "잇팁",
  isfp: "잇프피",
  estp: "엣팁",
  esfp: "엣프피",
};
